import {
  Dumbbell,
  Users,
  Activity,
  Flame,
  Target,
  HeartPulse,
} from "lucide-react";

export const siteData = {
  navLinks: [
    { label: "หน้าแรก", href: "/" },
    { label: "บริการ", href: "/services" },
    { label: "แพ็กเกจ", href: "/packages" },
    { label: "เทรนเนอร์", href: "/trainers" },
    { label: "รีวิว", href: "/reviews" },
    { label: "ติดต่อเรา", href: "/contact" },
  ],
  heroStats: [
    { label: "สมาชิก", value: "500+" },
    { label: "อุปกรณ์", value: "20+" },
    { label: "คลาสต่อสัปดาห์", value: "10+" },
    { label: "เทรนเนอร์", value: "5+" },
  ],
  services: [
    {
      id: "01",
      title: "ฟิตเนสเทรนนิ่ง",
      description: "ฝึกออกกำลังกายด้วยอุปกรณ์ครบครัน ทั้งเวทเทรนนิ่ง คาร์ดิโอ และเครื่องออกกำลังกายสำหรับทุกส่วนของร่างกาย",
      icon: Dumbbell,
      benefits: ["เพิ่มความแข็งแรง", "เสริมสร้างกล้ามเนื้อ", "พัฒนาความทนทาน"],
      suitableFor: "ผู้ที่ต้องการความยืดหยุ่นในการออกกำลังกายด้วยตัวเอง",
      image: "/images/gym-equipment.webp",
    },
    {
      id: "02",
      title: "เทรนเนอร์ส่วนตัว",
      description: "วางแผนการฝึกเฉพาะบุคคล แนะนำท่าที่ถูกต้อง และติดตามผลลัพธ์ให้เหมาะกับเป้าหมายของคุณ",
      icon: Users,
      benefits: ["ดูแลอย่างใกล้ชิด", "ป้องกันอาการบาดเจ็บ", "เห็นผลเร็วขึ้น"],
      suitableFor: "มือใหม่และผู้ที่ต้องการบรรลุเป้าหมายอย่างจริงจัง",
      image: "/images/personal-training.webp",
    },
    {
      id: "03",
      title: "โปรแกรมลดน้ำหนัก",
      description: "โปรแกรมลดไขมันและปรับรูปร่าง สำหรับผู้ที่ต้องการเปลี่ยนแปลงตัวเองอย่างปลอดภัยและยั่งยืน",
      icon: Flame,
      benefits: ["ลดไขมันสะสม", "กระชับสัดส่วน", "ปรับระบบเผาผลาญ"],
      suitableFor: "ผู้ที่ต้องการลดน้ำหนักอย่างถูกวิธี ไม่โยโย่",
      image: "/images/weight-room.webp",
    },
    {
      id: "04",
      title: "เพิ่มกล้ามเนื้อ",
      description: "ออกแบบโปรแกรมเพื่อสร้างกล้ามเนื้อ เพิ่มความแข็งแรง และพัฒนารูปร่างให้ชัดเจนขึ้น",
      icon: Target,
      benefits: ["กล้ามเนื้อชัดเจน", "เพิ่มขนาดร่างกาย", "เพิ่มพละกำลัง"],
      suitableFor: "ผู้ที่ต้องการเพิ่มขนาดตัวและกล้ามเนื้อ",
      image: "/images/strength-training.webp",
    },
    {
      id: "05",
      title: "คลาสกลุ่ม",
      description: "เพิ่มแรงจูงใจด้วยคลาสออกกำลังกายแบบกลุ่ม เช่น HIIT, Boxing, Cardio และ Functional Training",
      icon: Activity,
      benefits: ["สนุกสนาน", "เบิร์นแคลอรี่ได้เยอะ", "มีเพื่อนร่วมคลาส"],
      suitableFor: "ผู้ที่ชอบความสนุกและต้องการแรงผลักดัน",
      image: "/images/gym-class.webp",
    },
    {
      id: "06",
      title: "ให้คำปรึกษาด้านสุขภาพ",
      description: "แนะนำแนวทางการออกกำลังกายเบื้องต้น การตั้งเป้าหมาย และการดูแลสุขภาพให้เหมาะกับไลฟ์สไตล์",
      icon: HeartPulse,
      benefits: ["เข้าใจหลักโภชนาการ", "วางแผนการใช้ชีวิต", "ปรับพฤติกรรม"],
      suitableFor: "ทุกคนที่ต้องการเริ่มต้นดูแลสุขภาพอย่างยั่งยืน",
      image: "/images/health-consult.webp",
    },
  ],
  facilities: [
    "โซนเวทเทรนนิ่ง",
    "โซนคาร์ดิโอ",
    "โซนฝึกกล้ามเนื้อเฉพาะส่วน",
    "ห้องเปลี่ยนเสื้อผ้า",
    "ล็อกเกอร์ส่วนตัว",
    "พื้นที่พักผ่อน",
    "ที่จอดรถ",
    "ระบบระบายอากาศดี",
  ],
  trainers: [
    {
      name: "Coach Arm",
      specialty: "Weight Loss / Strength Training",
      description: "เชี่ยวชาญด้านการลดไขมันและสร้างความแข็งแรงสำหรับผู้เริ่มต้น",
      image: "/images/strength-training.webp",
      experience: "5 ปี",
      style: "เข้มงวดแต่ใส่ใจ เน้นท่าทางที่ถูกต้อง",
    },
    {
      name: "Coach May",
      specialty: "Functional Training / HIIT",
      description: "ออกแบบโปรแกรมฝึกที่สนุก ท้าทาย และเหมาะกับเป้าหมายเฉพาะบุคคล",
      image: "/images/coach-may.webp",
      experience: "4 ปี",
      style: "พลังเยอะ สนุกสนาน กระตุ้นเก่ง",
    },
    {
      name: "Coach Bank",
      specialty: "Muscle Building / Body Transformation",
      description: "ดูแลการเพิ่มกล้ามเนื้อและปรับรูปร่างอย่างเป็นระบบ",
      image: "/images/gym-equipment.webp",
      experience: "7 ปี",
      style: "มีระเบียบแบบแผน เน้นผลลัพธ์ที่จับต้องได้",
    },
  ],
  packages: [
    {
      name: "STARTER",
      thaiName: "แพ็กเกจเริ่มต้น",
      price: "฿999",
      period: " / เดือน",
      features: [
        "เข้าใช้งานฟิตเนส",
        "ใช้อุปกรณ์พื้นฐานครบ",
        "เหมาะสำหรับผู้เริ่มต้น",
        "รองรับทุกช่วงเวลาเปิดบริการ",
      ],
      buttonText: "สมัคร STARTER",
      popular: false,
    },
    {
      name: "PRO",
      thaiName: "แพ็กเกจยอดนิยม",
      price: "฿1,990",
      period: " / เดือน",
      features: [
        "เข้าใช้งานฟิตเนสไม่จำกัด",
        "ใช้อุปกรณ์ครบทุกโซน",
        "เข้าร่วมคลาสกลุ่ม",
        "รับคำแนะนำเบื้องต้นจากเทรนเนอร์",
      ],
      buttonText: "สมัคร PRO",
      popular: true,
    },
    {
      name: "ELITE",
      thaiName: "แพ็กเกจดูแลใกล้ชิด",
      price: "฿3,990",
      period: " / เดือน",
      features: [
        "เข้าใช้งานฟิตเนสไม่จำกัด",
        "Personal Trainer 4 ครั้ง",
        "วางแผนการฝึกเฉพาะบุคคล",
        "ติดตามผลลัพธ์ทุกสัปดาห์",
        "เหมาะกับเป้าหมายจริงจัง",
      ],
      buttonText: "ติดต่อ ELITE",
      popular: false,
    },
  ],
  transformations: [
    {
      goal: "ลดไขมัน",
      duration: "3 เดือน",
      testimonial: "จากคนที่ไม่เคยออกกำลังกาย สู่การมีวินัยและรูปร่างที่มั่นใจขึ้นภายใน 3 เดือน",
      image: "/images/transformation.webp",
    },
    {
      goal: "เพิ่มกล้ามเนื้อ",
      duration: "6 เดือน",
      testimonial: "น้ำหนักขึ้นพร้อมกล้ามเนื้อที่ชัดเจนขึ้น รู้สึกแข็งแรงและสุขภาพดีกว่าที่เคย",
      image: "/images/gym-equipment.webp",
    },
    {
      goal: "สุขภาพแข็งแรงขึ้น",
      duration: "2 เดือน",
      testimonial: "ระบบเผาผลาญดีขึ้น เหนื่อยน้อยลง มีพลังในการใช้ชีวิตประจำวันมากขึ้น",
      image: "/images/strength-training.webp",
    },
  ],
  testimonials: [
    {
      name: "คุณเอก",
      review: "เริ่มแรกไม่มั่นใจเลยว่าจะเล่นเวทถูกไหม แต่เทรนเนอร์ให้คำแนะนำดีมาก ตอนนี้ออกกำลังกายสม่ำเสมอขึ้นและรู้สึกแข็งแรงกว่าเดิม",
      rating: 5,
    },
    {
      name: "คุณพลอย",
      review: "บรรยากาศยิมดี อุปกรณ์ครบ คนไม่อึดอัด เหมาะกับคนที่อยากเริ่มออกกำลังกายแบบจริงจัง แต่ก็มีความเป็นส่วนตัวสูง",
      rating: 5,
    },
    {
      name: "คุณบอย",
      review: "ชอบที่มีคนคอยแนะนำ ไม่ได้ปล่อยให้เล่นเองแบบงง ๆ ทำให้มั่นใจมากขึ้น รูปร่างเปลี่ยนไปอย่างเห็นได้ชัดใน 3 เดือน",
      rating: 5,
    },
  ],
  gallery: [
    "/images/gym-equipment.webp",
    "/images/personal-training.webp",
    "/images/weight-room.webp",
    "/images/gym-class.webp",
    "/images/strength-training.webp",
    "/images/health-consult.webp",
  ],
};
